# Generated by Django 2.1.7 on 2019-03-24 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0005_auto_20190324_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryPage',
        ),
    ]
