version: "3.7"

services:

  backend:
    build:
      context: ./backend
    ports:
      - 127.0.0.1:8000:8000
    command: python manage.py runserver

  frontend:
    image: node:latest
    ports:
      - 127.0.0.1:3000:3000
    command: yarn && yarn start
